"""
api/schemas.py — Pydantic v2 request / response models for SROP.

All UUID fields are typed as uuid.UUID so FastAPI serialises them as strings
automatically.  The OrmBase class enables from_attributes for SQLAlchemy →
Pydantic conversion.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


# ── Shared base ───────────────────────────────────────────────────────────────

class OrmBase(BaseModel):
    """Base that enables ORM mode (SQLAlchemy → Pydantic)."""

    model_config = ConfigDict(from_attributes=True)


# ── POST /v1/sessions ─────────────────────────────────────────────────────────

class CreateSessionRequest(BaseModel):
    """Payload required to open a new session."""

    user_id: str = Field(..., min_length=1, max_length=255, description="Caller user identifier")
    plan_tier: Literal["free", "pro", "enterprise"] = Field(
        default="free",
        description="Subscription tier controlling rate limits and feature access",
    )


class CreateSessionResponse(BaseModel):
    """Minimal response: only the new session UUID is returned."""

    session_id: UUID = Field(..., description="Newly created session identifier")


# ── POST /v1/chat/{session_id} ────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """User turn payload."""

    message: str = Field(..., min_length=1, description="User's message text")


class ChatResponse(BaseModel):
    """Assistant reply with routing and observability metadata."""

    reply: str = Field(..., description="Text generated by the active sub-agent")
    routed_to: str = Field(..., description="Name of the sub-agent that handled this turn")
    trace_id: UUID = Field(..., description="ID of the AgentTrace row for this turn")


# ── GET /v1/traces/{trace_id} ─────────────────────────────────────────────────

class TraceResponse(OrmBase):
    """Full agent trace record."""

    trace_id: UUID = Field(alias="id", description="Trace primary key")
    session_id: UUID = Field(..., description="Parent session identifier")
    routed_to: str = Field(..., description="Sub-agent name")
    tool_calls: list[dict[str, Any]] = Field(
        default_factory=list, description="Tool invocations recorded during the turn"
    )
    retrieved_chunk_ids: list[str] = Field(
        default_factory=list, description="Vector-store chunk IDs used for context"
    )
    latency_ms: int = Field(..., description="End-to-end pipeline latency in milliseconds")
    created_at: datetime = Field(..., description="UTC timestamp of trace creation")

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


# ── /healthz ──────────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str = "ok"
